; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare_esp32s3_relay]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_src_filter =
	-<*>
	+<main.cpp>
	+<ESP32-S3-POE-ETH-8DI-8RO-Demo/Arduino/examples/MAIN_WIFI_AP/I2C_Driver.cpp>
	+<ESP32-S3-POE-ETH-8DI-8RO-Demo/Arduino/examples/MAIN_WIFI_AP/WS_GPIO.cpp>
	+<ESP32-S3-POE-ETH-8DI-8RO-Demo/Arduino/examples/MAIN_WIFI_AP/WS_PCF85063.cpp>
	+<ESP32-S3-POE-ETH-8DI-8RO-Demo/Arduino/examples/MAIN_WIFI_AP/WS_RTC.cpp>
	+<ESP32-S3-POE-ETH-8DI-8RO-Demo/Arduino/examples/MAIN_WIFI_AP/WS_Relay.cpp>
	+<ESP32-S3-POE-ETH-8DI-8RO-Demo/Arduino/examples/MAIN_WIFI_AP/WS_TCA9554PWR.cpp>
	+<ESP32-S3-POE-ETH-8DI-8RO-Demo/Arduino/examples/MAIN_WIFI_AP/WS_WIFI.cpp>
build_flags = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D BOARD_HAS_PSRAM
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8
	arduino-libraries/NTPClient@^3.2.1
