; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:billiard_parent]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_flags = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D BOARD_HAS_PSRAM
	-D WIFI_SSID=\"THUNDER.LNET.GUEST\"
	-D WIFI_PASSWORD=\"\"
	-D WIFI_HOSTNAME=\"billiard-iot\"
lib_extra_dirs =
	../shared
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8
	arduino-libraries/NTPClient@^3.2.1
